//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicGeometry.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicGeometry.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap DGArc {
            get {
                object obj = ResourceManager.GetObject("DGArc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGBisector {
            get {
                object obj = ResourceManager.GetObject("DGBisector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGCircle {
            get {
                object obj = ResourceManager.GetObject("DGCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGCircleByRadius {
            get {
                object obj = ResourceManager.GetObject("DGCircleByRadius", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGDLocus {
            get {
                object obj = ResourceManager.GetObject("DGDLocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGIntersect {
            get {
                object obj = ResourceManager.GetObject("DGIntersect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGInvert {
            get {
                object obj = ResourceManager.GetObject("DGInvert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGLine {
            get {
                object obj = ResourceManager.GetObject("DGLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGLineParallel {
            get {
                object obj = ResourceManager.GetObject("DGLineParallel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGLinePerpendicular {
            get {
                object obj = ResourceManager.GetObject("DGLinePerpendicular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGMeasureAngle {
            get {
                object obj = ResourceManager.GetObject("DGMeasureAngle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGMeasureArea {
            get {
                object obj = ResourceManager.GetObject("DGMeasureArea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGMeasureDistance {
            get {
                object obj = ResourceManager.GetObject("DGMeasureDistance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGMidPoint {
            get {
                object obj = ResourceManager.GetObject("DGMidPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGNew {
            get {
                object obj = ResourceManager.GetObject("DGNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGOpen {
            get {
                object obj = ResourceManager.GetObject("DGOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGPoint {
            get {
                object obj = ResourceManager.GetObject("DGPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGPointer {
            get {
                object obj = ResourceManager.GetObject("DGPointer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGPointOnFigure {
            get {
                object obj = ResourceManager.GetObject("DGPointOnFigure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGPolygon {
            get {
                object obj = ResourceManager.GetObject("DGPolygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGRay {
            get {
                object obj = ResourceManager.GetObject("DGRay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGRedo {
            get {
                object obj = ResourceManager.GetObject("DGRedo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGSave {
            get {
                object obj = ResourceManager.GetObject("DGSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGSegment {
            get {
                object obj = ResourceManager.GetObject("DGSegment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGSimmPoint {
            get {
                object obj = ResourceManager.GetObject("DGSimmPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGSimmPointByLine {
            get {
                object obj = ResourceManager.GetObject("DGSimmPointByLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGToolDynamicLocus {
            get {
                object obj = ResourceManager.GetObject("DGToolDynamicLocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGToolPoint {
            get {
                object obj = ResourceManager.GetObject("DGToolPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGToolPolygon {
            get {
                object obj = ResourceManager.GetObject("DGToolPolygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGUndo {
            get {
                object obj = ResourceManager.GetObject("DGUndo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWArc {
            get {
                object obj = ResourceManager.GetObject("DGWArc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWBisector {
            get {
                object obj = ResourceManager.GetObject("DGWBisector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWCircle {
            get {
                object obj = ResourceManager.GetObject("DGWCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWCircleByRadius {
            get {
                object obj = ResourceManager.GetObject("DGWCircleByRadius", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWDLocus {
            get {
                object obj = ResourceManager.GetObject("DGWDLocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWIntersect {
            get {
                object obj = ResourceManager.GetObject("DGWIntersect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWInvert {
            get {
                object obj = ResourceManager.GetObject("DGWInvert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWLine {
            get {
                object obj = ResourceManager.GetObject("DGWLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWLineParallel {
            get {
                object obj = ResourceManager.GetObject("DGWLineParallel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWLinePerpendicular {
            get {
                object obj = ResourceManager.GetObject("DGWLinePerpendicular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWMeasureAngle {
            get {
                object obj = ResourceManager.GetObject("DGWMeasureAngle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWMeasureArea {
            get {
                object obj = ResourceManager.GetObject("DGWMeasureArea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWMeasureDistance {
            get {
                object obj = ResourceManager.GetObject("DGWMeasureDistance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWMidPoint {
            get {
                object obj = ResourceManager.GetObject("DGWMidPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWNew {
            get {
                object obj = ResourceManager.GetObject("DGWNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWOpen {
            get {
                object obj = ResourceManager.GetObject("DGWOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWPoint {
            get {
                object obj = ResourceManager.GetObject("DGWPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWPointer {
            get {
                object obj = ResourceManager.GetObject("DGWPointer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWPointOnFigure {
            get {
                object obj = ResourceManager.GetObject("DGWPointOnFigure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWPolygon {
            get {
                object obj = ResourceManager.GetObject("DGWPolygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWRay {
            get {
                object obj = ResourceManager.GetObject("DGWRay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWRedo {
            get {
                object obj = ResourceManager.GetObject("DGWRedo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWSave {
            get {
                object obj = ResourceManager.GetObject("DGWSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWSegment {
            get {
                object obj = ResourceManager.GetObject("DGWSegment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWSimmPoint {
            get {
                object obj = ResourceManager.GetObject("DGWSimmPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWSimmPointByLine {
            get {
                object obj = ResourceManager.GetObject("DGWSimmPointByLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWToolDynamicLocus {
            get {
                object obj = ResourceManager.GetObject("DGWToolDynamicLocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWToolPoint {
            get {
                object obj = ResourceManager.GetObject("DGWToolPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWToolPolygon {
            get {
                object obj = ResourceManager.GetObject("DGWToolPolygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DGWUndo {
            get {
                object obj = ResourceManager.GetObject("DGWUndo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
