//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50401.0
// 
namespace LiveGeometry.LiveGeometryWebServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://livegeometry.com/", ConfigurationName="LiveGeometryWebServices.LiveGeometrySoap")]
    public interface LiveGeometrySoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://livegeometry.com/SendErrorReport", ReplyAction="*")]
        System.IAsyncResult BeginSendErrorReport(LiveGeometry.LiveGeometryWebServices.SendErrorReportRequest request, System.AsyncCallback callback, object asyncState);
        
        LiveGeometry.LiveGeometryWebServices.SendErrorReportResponse EndSendErrorReport(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://livegeometry.com/SendTabulaErrorReport", ReplyAction="*")]
        System.IAsyncResult BeginSendTabulaErrorReport(LiveGeometry.LiveGeometryWebServices.SendTabulaErrorReportRequest request, System.AsyncCallback callback, object asyncState);
        
        LiveGeometry.LiveGeometryWebServices.SendTabulaErrorReportResponse EndSendTabulaErrorReport(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendErrorReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendErrorReport", Namespace="http://livegeometry.com/", Order=0)]
        public LiveGeometry.LiveGeometryWebServices.SendErrorReportRequestBody Body;
        
        public SendErrorReportRequest() {
        }
        
        public SendErrorReportRequest(LiveGeometry.LiveGeometryWebServices.SendErrorReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://livegeometry.com/")]
    public partial class SendErrorReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string error;
        
        public SendErrorReportRequestBody() {
        }
        
        public SendErrorReportRequestBody(string error) {
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendErrorReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendErrorReportResponse", Namespace="http://livegeometry.com/", Order=0)]
        public LiveGeometry.LiveGeometryWebServices.SendErrorReportResponseBody Body;
        
        public SendErrorReportResponse() {
        }
        
        public SendErrorReportResponse(LiveGeometry.LiveGeometryWebServices.SendErrorReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://livegeometry.com/")]
    public partial class SendErrorReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendErrorReportResult;
        
        public SendErrorReportResponseBody() {
        }
        
        public SendErrorReportResponseBody(string SendErrorReportResult) {
            this.SendErrorReportResult = SendErrorReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTabulaErrorReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTabulaErrorReport", Namespace="http://livegeometry.com/", Order=0)]
        public LiveGeometry.LiveGeometryWebServices.SendTabulaErrorReportRequestBody Body;
        
        public SendTabulaErrorReportRequest() {
        }
        
        public SendTabulaErrorReportRequest(LiveGeometry.LiveGeometryWebServices.SendTabulaErrorReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://livegeometry.com/")]
    public partial class SendTabulaErrorReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string error;
        
        public SendTabulaErrorReportRequestBody() {
        }
        
        public SendTabulaErrorReportRequestBody(string error) {
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTabulaErrorReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTabulaErrorReportResponse", Namespace="http://livegeometry.com/", Order=0)]
        public LiveGeometry.LiveGeometryWebServices.SendTabulaErrorReportResponseBody Body;
        
        public SendTabulaErrorReportResponse() {
        }
        
        public SendTabulaErrorReportResponse(LiveGeometry.LiveGeometryWebServices.SendTabulaErrorReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://livegeometry.com/")]
    public partial class SendTabulaErrorReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendTabulaErrorReportResult;
        
        public SendTabulaErrorReportResponseBody() {
        }
        
        public SendTabulaErrorReportResponseBody(string SendTabulaErrorReportResult) {
            this.SendTabulaErrorReportResult = SendTabulaErrorReportResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LiveGeometrySoapChannel : LiveGeometry.LiveGeometryWebServices.LiveGeometrySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendErrorReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SendErrorReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendTabulaErrorReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SendTabulaErrorReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LiveGeometrySoapClient : System.ServiceModel.ClientBase<LiveGeometry.LiveGeometryWebServices.LiveGeometrySoap>, LiveGeometry.LiveGeometryWebServices.LiveGeometrySoap {
        
        private BeginOperationDelegate onBeginSendErrorReportDelegate;
        
        private EndOperationDelegate onEndSendErrorReportDelegate;
        
        private System.Threading.SendOrPostCallback onSendErrorReportCompletedDelegate;
        
        private BeginOperationDelegate onBeginSendTabulaErrorReportDelegate;
        
        private EndOperationDelegate onEndSendTabulaErrorReportDelegate;
        
        private System.Threading.SendOrPostCallback onSendTabulaErrorReportCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public LiveGeometrySoapClient() {
        }
        
        public LiveGeometrySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LiveGeometrySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiveGeometrySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiveGeometrySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<SendErrorReportCompletedEventArgs> SendErrorReportCompleted;
        
        public event System.EventHandler<SendTabulaErrorReportCompletedEventArgs> SendTabulaErrorReportCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LiveGeometry.LiveGeometryWebServices.LiveGeometrySoap.BeginSendErrorReport(LiveGeometry.LiveGeometryWebServices.SendErrorReportRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSendErrorReport(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginSendErrorReport(string error, System.AsyncCallback callback, object asyncState) {
            LiveGeometry.LiveGeometryWebServices.SendErrorReportRequest inValue = new LiveGeometry.LiveGeometryWebServices.SendErrorReportRequest();
            inValue.Body = new LiveGeometry.LiveGeometryWebServices.SendErrorReportRequestBody();
            inValue.Body.error = error;
            return ((LiveGeometry.LiveGeometryWebServices.LiveGeometrySoap)(this)).BeginSendErrorReport(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LiveGeometry.LiveGeometryWebServices.SendErrorReportResponse LiveGeometry.LiveGeometryWebServices.LiveGeometrySoap.EndSendErrorReport(System.IAsyncResult result) {
            return base.Channel.EndSendErrorReport(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndSendErrorReport(System.IAsyncResult result) {
            LiveGeometry.LiveGeometryWebServices.SendErrorReportResponse retVal = ((LiveGeometry.LiveGeometryWebServices.LiveGeometrySoap)(this)).EndSendErrorReport(result);
            return retVal.Body.SendErrorReportResult;
        }
        
        private System.IAsyncResult OnBeginSendErrorReport(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string error = ((string)(inValues[0]));
            return this.BeginSendErrorReport(error, callback, asyncState);
        }
        
        private object[] OnEndSendErrorReport(System.IAsyncResult result) {
            string retVal = this.EndSendErrorReport(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSendErrorReportCompleted(object state) {
            if ((this.SendErrorReportCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SendErrorReportCompleted(this, new SendErrorReportCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SendErrorReportAsync(string error) {
            this.SendErrorReportAsync(error, null);
        }
        
        public void SendErrorReportAsync(string error, object userState) {
            if ((this.onBeginSendErrorReportDelegate == null)) {
                this.onBeginSendErrorReportDelegate = new BeginOperationDelegate(this.OnBeginSendErrorReport);
            }
            if ((this.onEndSendErrorReportDelegate == null)) {
                this.onEndSendErrorReportDelegate = new EndOperationDelegate(this.OnEndSendErrorReport);
            }
            if ((this.onSendErrorReportCompletedDelegate == null)) {
                this.onSendErrorReportCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSendErrorReportCompleted);
            }
            base.InvokeAsync(this.onBeginSendErrorReportDelegate, new object[] {
                        error}, this.onEndSendErrorReportDelegate, this.onSendErrorReportCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LiveGeometry.LiveGeometryWebServices.LiveGeometrySoap.BeginSendTabulaErrorReport(LiveGeometry.LiveGeometryWebServices.SendTabulaErrorReportRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSendTabulaErrorReport(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginSendTabulaErrorReport(string error, System.AsyncCallback callback, object asyncState) {
            LiveGeometry.LiveGeometryWebServices.SendTabulaErrorReportRequest inValue = new LiveGeometry.LiveGeometryWebServices.SendTabulaErrorReportRequest();
            inValue.Body = new LiveGeometry.LiveGeometryWebServices.SendTabulaErrorReportRequestBody();
            inValue.Body.error = error;
            return ((LiveGeometry.LiveGeometryWebServices.LiveGeometrySoap)(this)).BeginSendTabulaErrorReport(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LiveGeometry.LiveGeometryWebServices.SendTabulaErrorReportResponse LiveGeometry.LiveGeometryWebServices.LiveGeometrySoap.EndSendTabulaErrorReport(System.IAsyncResult result) {
            return base.Channel.EndSendTabulaErrorReport(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndSendTabulaErrorReport(System.IAsyncResult result) {
            LiveGeometry.LiveGeometryWebServices.SendTabulaErrorReportResponse retVal = ((LiveGeometry.LiveGeometryWebServices.LiveGeometrySoap)(this)).EndSendTabulaErrorReport(result);
            return retVal.Body.SendTabulaErrorReportResult;
        }
        
        private System.IAsyncResult OnBeginSendTabulaErrorReport(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string error = ((string)(inValues[0]));
            return this.BeginSendTabulaErrorReport(error, callback, asyncState);
        }
        
        private object[] OnEndSendTabulaErrorReport(System.IAsyncResult result) {
            string retVal = this.EndSendTabulaErrorReport(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSendTabulaErrorReportCompleted(object state) {
            if ((this.SendTabulaErrorReportCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SendTabulaErrorReportCompleted(this, new SendTabulaErrorReportCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SendTabulaErrorReportAsync(string error) {
            this.SendTabulaErrorReportAsync(error, null);
        }
        
        public void SendTabulaErrorReportAsync(string error, object userState) {
            if ((this.onBeginSendTabulaErrorReportDelegate == null)) {
                this.onBeginSendTabulaErrorReportDelegate = new BeginOperationDelegate(this.OnBeginSendTabulaErrorReport);
            }
            if ((this.onEndSendTabulaErrorReportDelegate == null)) {
                this.onEndSendTabulaErrorReportDelegate = new EndOperationDelegate(this.OnEndSendTabulaErrorReport);
            }
            if ((this.onSendTabulaErrorReportCompletedDelegate == null)) {
                this.onSendTabulaErrorReportCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSendTabulaErrorReportCompleted);
            }
            base.InvokeAsync(this.onBeginSendTabulaErrorReportDelegate, new object[] {
                        error}, this.onEndSendTabulaErrorReportDelegate, this.onSendTabulaErrorReportCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override LiveGeometry.LiveGeometryWebServices.LiveGeometrySoap CreateChannel() {
            return new LiveGeometrySoapClientChannel(this);
        }
        
        private class LiveGeometrySoapClientChannel : ChannelBase<LiveGeometry.LiveGeometryWebServices.LiveGeometrySoap>, LiveGeometry.LiveGeometryWebServices.LiveGeometrySoap {
            
            public LiveGeometrySoapClientChannel(System.ServiceModel.ClientBase<LiveGeometry.LiveGeometryWebServices.LiveGeometrySoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginSendErrorReport(LiveGeometry.LiveGeometryWebServices.SendErrorReportRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("SendErrorReport", _args, callback, asyncState);
                return _result;
            }
            
            public LiveGeometry.LiveGeometryWebServices.SendErrorReportResponse EndSendErrorReport(System.IAsyncResult result) {
                object[] _args = new object[0];
                LiveGeometry.LiveGeometryWebServices.SendErrorReportResponse _result = ((LiveGeometry.LiveGeometryWebServices.SendErrorReportResponse)(base.EndInvoke("SendErrorReport", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSendTabulaErrorReport(LiveGeometry.LiveGeometryWebServices.SendTabulaErrorReportRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("SendTabulaErrorReport", _args, callback, asyncState);
                return _result;
            }
            
            public LiveGeometry.LiveGeometryWebServices.SendTabulaErrorReportResponse EndSendTabulaErrorReport(System.IAsyncResult result) {
                object[] _args = new object[0];
                LiveGeometry.LiveGeometryWebServices.SendTabulaErrorReportResponse _result = ((LiveGeometry.LiveGeometryWebServices.SendTabulaErrorReportResponse)(base.EndInvoke("SendTabulaErrorReport", _args, result)));
                return _result;
            }
        }
    }
}
